# PROMPT:
# I need a validation suite for the visitor registry service responsible for maintaining customer records generated by the tracking engine.
#
# The goal is to ensure that visitor information remains accurate, unique, and synchronized across the analytics workflow.
#
# The test should validate:
# - Visitor creation
# - Visitor updates
# - Duplicate prevention
# - Lookup functionality
# - Registry consistency over time
#
# This component is important because occupancy analytics and visitor behavior reporting depend on accurate visitor records.
#
# CHANGES MADE:
# Added project-specific visitor lifecycle scenarios and consistency checks.
#
from pipeline.visitor_registry import VisitorRegistry

registry = VisitorRegistry()

registry.register("VIS_001")
registry.register("VIS_002")

print(registry.count())
print(registry.get("VIS_001"))
